/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){function e(e,t,r){if(r){return t?t(e):e}if(!e||!e.then){e=Promise.resolve(e)}return t?e.then(t):e}sap.ui.define(["./DataSourceType","./FacetQuery"],function(t,r){function n(e,t){if(!(e instanceof t)){throw new TypeError("Cannot call a class as a function")}}function o(e,t){for(var r=0;r<t.length;r++){var n=t[r];n.enumerable=n.enumerable||false;n.configurable=true;if("value"in n)n.writable=true;Object.defineProperty(e,n.key,n)}}function i(e,t,r){if(t)o(e.prototype,t);if(r)o(e,r);Object.defineProperty(e,"prototype",{writable:false});return e}function u(){if(typeof Reflect!=="undefined"&&Reflect.get){u=Reflect.get.bind()}else{u=function e(t,r,n){var o=c(t,r);if(!o)return;var i=Object.getOwnPropertyDescriptor(o,r);if(i.get){return i.get.call(arguments.length<3?t:n)}return i.value}}return u.apply(this,arguments)}function c(e,t){while(!Object.prototype.hasOwnProperty.call(e,t)){e=d(e);if(e===null)break}return e}function f(e,t){if(typeof t!=="function"&&t!==null){throw new TypeError("Super expression must either be null or a function")}e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,writable:true,configurable:true}});Object.defineProperty(e,"prototype",{writable:false});if(t)a(e,t)}function a(e,t){a=Object.setPrototypeOf?Object.setPrototypeOf.bind():function e(t,r){t.__proto__=r;return t};return a(e,t)}function l(e){var t=p();return function r(){var n=d(e),o;if(t){var i=d(this).constructor;o=Reflect.construct(n,arguments,i)}else{o=n.apply(this,arguments)}return s(this,o)}}function s(e,t){if(t&&(typeof t==="object"||typeof t==="function")){return t}else if(t!==void 0){throw new TypeError("Derived constructors may only return object or undefined")}return y(e)}function y(e){if(e===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return e}function p(){if(typeof Reflect==="undefined"||!Reflect.construct)return false;if(Reflect.construct.sham)return false;if(typeof Proxy==="function")return true;try{Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}));return true}catch(e){return false}}function d(e){d=Object.setPrototypeOf?Object.getPrototypeOf.bind():function e(t){return t.__proto__||Object.getPrototypeOf(t)};return d(e)}function h(e,t,r){if(t in e){Object.defineProperty(e,t,{value:r,enumerable:true,configurable:true,writable:true})}else{e[t]=r}return e}
/*!
   * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
   */var b=t["DataSourceSubType"];var v=t["DataSourceType"];var m=r["FacetQuery"];var O=function(t){f(o,t);var r=l(o);function o(e){var t,i;var u;n(this,o);u=r.call(this,e);h(y(u),"top",5);u.top=(t=e.top)!==null&&t!==void 0?t:u.top;u.dimension=(i=e.dimension)!==null&&i!==void 0?i:u.dimension;return u}i(o,[{key:"equals",value:function e(t){return t instanceof o&&u(d(o.prototype),"equals",this).call(this,t)&&this.dimension===t.dimension}},{key:"clone",value:function e(){return new o({label:this.label,icon:this.icon,skip:this.skip,top:this.top,sortOrder:this.sortOrder,filter:this.filter.clone(),sina:this.sina,dimension:this.dimension})}},{key:"_formatResultSetAsync",value:function e(t){return Promise.resolve()}},{key:"_execute",value:function t(r){try{const t=this;return e(t._doExecuteChartQuery(r))}catch(e){return Promise.reject(e)}}},{key:"_doExecuteChartQuery",value:function t(r){try{const t=this;var n=t._filteredQueryTransform(r);return e(t.sina.provider.executeChartQuery(n),function(e){return t._filteredQueryBackTransform(r,e)})}catch(e){return Promise.reject(e)}}},{key:"_filteredQueryTransform",value:function e(t){return this._genericFilteredQueryTransform(t)}},{key:"_filteredQueryBackTransform",value:function e(t,r){if(t.filter.dataSource.type!==v.BusinessObject||t.filter.dataSource.subType!==b.Filtered){return r}r.query=t;return r}}]);return o}(m);var _={__esModule:true};_.ChartQuery=O;return _})})();
//# sourceMappingURL=ChartQuery.js.map