/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 *      (c) Copyright 2009-2023 SAP SE. All rights reserved
 */
sap.ui.define(["sap/fe/core/buildingBlocks/BuildingBlock","sap/fe/core/buildingBlocks/BuildingBlockRuntime","sap/fe/core/converters/MetaModelConverter"],function(e,t,i){"use strict";var r,l,n,a,o,u,s,c,f,b,d,p,m,v,g,h,y;var z={};var P=i.getInvolvedDataModelObjects;var w=t.xml;var k=e.defineBuildingBlock;var B=e.BuildingBlockBase;var O=e.blockAttribute;var x=e.blockAggregation;function j(e,t,i,r){if(!i)return;Object.defineProperty(e,t,{enumerable:i.enumerable,configurable:i.configurable,writable:i.writable,value:i.initializer?i.initializer.call(r):void 0})}function F(e){if(e===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return e}function $(e,t){e.prototype=Object.create(t.prototype);e.prototype.constructor=e;E(e,t)}function E(e,t){E=Object.setPrototypeOf?Object.setPrototypeOf.bind():function e(t,i){t.__proto__=i;return t};return E(e,t)}function C(e,t,i,r,l){var n={};Object.keys(r).forEach(function(e){n[e]=r[e]});n.enumerable=!!n.enumerable;n.configurable=!!n.configurable;if("value"in n||n.initializer){n.writable=true}n=i.slice().reverse().reduce(function(i,r){return r(e,t,i)||i},n);if(l&&n.initializer!==void 0){n.value=n.initializer?n.initializer.call(l):void 0;n.initializer=undefined}if(n.initializer===void 0){Object.defineProperty(e,t,n);n=null}return n}function _(e,t){throw new Error("Decorating class property failed. Please ensure that "+"proposal-class-properties is enabled and runs after the decorators transform.")}let q=(r=k({name:"FormElement",namespace:"sap.fe.macros"}),l=O({type:"string",required:true}),n=O({type:"sap.ui.model.Context",required:true}),a=O({type:"sap.ui.model.Context",required:true}),o=O({type:"string"}),u=O({type:"boolean"}),s=O({type:"string"}),c=x({type:"sap.ui.core.Control",slot:"fields",isDefault:true}),r(f=(b=function(e){$(t,e);function t(t,i,r){var l;l=e.call(this,t,i,r)||this;j(l,"id",d,F(l));j(l,"contextPath",p,F(l));j(l,"metaPath",m,F(l));j(l,"label",v,F(l));j(l,"visible",g,F(l));j(l,"key",h,F(l));j(l,"fields",y,F(l));const n=P(l.metaPath,l.contextPath);if(l.label===undefined){var a,o;l.label=((a=n.targetObject.annotations.Common)===null||a===void 0?void 0:(o=a.Label)===null||o===void 0?void 0:o.toString())??""}return l}z=t;var i=t.prototype;i.getFields=function e(){if(this.fields){return w`<slot name="fields" />`}else{return w`<macros:Field
						metaPath="${this.metaPath}"
						contextPath="${this.contextPath}"
						id="${this.createId("FormElementField")}" />`}};i.getTemplate=function e(){return w`<f:FormElement xmlns:f="sap.ui.layout.form" id="${this.id}"
			key="${this.key}"
			label="${this.label}"
			visible="${this.visible}">
			<f:fields>
				${this.getFields()}
			</f:fields>
		</f:FormElement>`};return t}(B),d=C(b.prototype,"id",[l],{configurable:true,enumerable:true,writable:true,initializer:null}),p=C(b.prototype,"contextPath",[n],{configurable:true,enumerable:true,writable:true,initializer:null}),m=C(b.prototype,"metaPath",[a],{configurable:true,enumerable:true,writable:true,initializer:null}),v=C(b.prototype,"label",[o],{configurable:true,enumerable:true,writable:true,initializer:null}),g=C(b.prototype,"visible",[u],{configurable:true,enumerable:true,writable:true,initializer:null}),h=C(b.prototype,"key",[s],{configurable:true,enumerable:true,writable:true,initializer:null}),y=C(b.prototype,"fields",[c],{configurable:true,enumerable:true,writable:true,initializer:null}),b))||f);z=q;return z},false);
//# sourceMappingURL=FormElementBlock.js.map